### ISSUE TITLE
Instructions in readme propose non-functional workflows

### ISSUE THREAD

**Issue by mheguy** [advanced-security/python-lint-code-scanning-action#11]
https://github.com/advanced-security/python-lint-code-scanning-action#call-the-action-with-a-workflow

The readme has the key `use` in the context of github workflows.
`use` is not a valid key though, the correct key is `uses`.

Even with that fixed, the workflow will not run as the codebase has not been checked out.

People experienced with github actions will recognize these issues quickly, but you risk giving headaches to new users.

**Comment by aegilops** [comment]
Thanks for the report! I've corrected that and will create a new release later
